-- migrate:up

ALTER TABLE import_metadata DISABLE ROW LEVEL SECURITY;
ALTER TABLE feed_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE agency DISABLE ROW LEVEL SECURITY;
ALTER TABLE calendar DISABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_dates DISABLE ROW LEVEL SECURITY;
ALTER TABLE routes DISABLE ROW LEVEL SECURITY;
ALTER TABLE frequencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE stops DISABLE ROW LEVEL SECURITY;
ALTER TABLE stop_times DISABLE ROW LEVEL SECURITY;
ALTER TABLE trips DISABLE ROW LEVEL SECURITY;

-- migrate:down

ALTER TABLE import_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE feed_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE agency ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE frequencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE stop_times ENABLE ROW LEVEL SECURITY;
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
