-- migrate:up

CREATE ROLE gtfs_import WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	BYPASSRLS
	NOLOGIN
	CONNECTION LIMIT -1;

GRANT USAGE, CREATE ON SCHEMA public TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.calendar TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.calendar_dates TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.feed_info TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.agency TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.import_metadata TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.routes TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.stop_times TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.stops TO gtfs_import;
GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLE public.trips TO gtfs_import;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, REFERENCES, TRUNCATE, TRIGGER, UPDATE, SELECT, DELETE ON TABLES TO gtfs_import;

-- migrate:down

DROP OWNED BY gtfs_import;
DROP ROLE gtfs_import;
