app = "transit-tracker-api-redis"
primary_region = "sjc"
swap_size_mb = 64

[build]
  # Assumes you are running this from repo root
  dockerfile = "deploy/redis/Dockerfile"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1